CC=gcc
cuadrado.o: cuadrado.c               
	$(CC) -c cuadrado.c

cubo.o: cubo.c               
	$(CC) -c cubo.c

cuarta.o: cuarta.c               
	$(CC) -c cuarta.c

clean:           	            
	rm  *.o
